//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace FactoriesCreator.SqlServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SqlServiceReference.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetSqlString", ReplyAction="*")]
        System.IAsyncResult BeginGetSqlString(FactoriesCreator.SqlServiceReference.GetSqlStringRequest request, System.AsyncCallback callback, object asyncState);
        
        FactoriesCreator.SqlServiceReference.GetSqlStringResponse EndGetSqlString(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSqlStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSqlString", Namespace="http://tempuri.org/", Order=0)]
        public FactoriesCreator.SqlServiceReference.GetSqlStringRequestBody Body;
        
        public GetSqlStringRequest() {
        }
        
        public GetSqlStringRequest(FactoriesCreator.SqlServiceReference.GetSqlStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSqlStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sql;
        
        public GetSqlStringRequestBody() {
        }
        
        public GetSqlStringRequestBody(string sql) {
            this.sql = sql;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSqlStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSqlStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public FactoriesCreator.SqlServiceReference.GetSqlStringResponseBody Body;
        
        public GetSqlStringResponse() {
        }
        
        public GetSqlStringResponse(FactoriesCreator.SqlServiceReference.GetSqlStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSqlStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetSqlStringResult;
        
        public GetSqlStringResponseBody() {
        }
        
        public GetSqlStringResponseBody(string GetSqlStringResult) {
            this.GetSqlStringResult = GetSqlStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : FactoriesCreator.SqlServiceReference.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetSqlStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetSqlStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<FactoriesCreator.SqlServiceReference.Service1Soap>, FactoriesCreator.SqlServiceReference.Service1Soap {
        
        private BeginOperationDelegate onBeginGetSqlStringDelegate;
        
        private EndOperationDelegate onEndGetSqlStringDelegate;
        
        private System.Threading.SendOrPostCallback onGetSqlStringCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetSqlStringCompletedEventArgs> GetSqlStringCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult FactoriesCreator.SqlServiceReference.Service1Soap.BeginGetSqlString(FactoriesCreator.SqlServiceReference.GetSqlStringRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetSqlString(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetSqlString(string sql, System.AsyncCallback callback, object asyncState) {
            FactoriesCreator.SqlServiceReference.GetSqlStringRequest inValue = new FactoriesCreator.SqlServiceReference.GetSqlStringRequest();
            inValue.Body = new FactoriesCreator.SqlServiceReference.GetSqlStringRequestBody();
            inValue.Body.sql = sql;
            return ((FactoriesCreator.SqlServiceReference.Service1Soap)(this)).BeginGetSqlString(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FactoriesCreator.SqlServiceReference.GetSqlStringResponse FactoriesCreator.SqlServiceReference.Service1Soap.EndGetSqlString(System.IAsyncResult result) {
            return base.Channel.EndGetSqlString(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetSqlString(System.IAsyncResult result) {
            FactoriesCreator.SqlServiceReference.GetSqlStringResponse retVal = ((FactoriesCreator.SqlServiceReference.Service1Soap)(this)).EndGetSqlString(result);
            return retVal.Body.GetSqlStringResult;
        }
        
        private System.IAsyncResult OnBeginGetSqlString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sql = ((string)(inValues[0]));
            return this.BeginGetSqlString(sql, callback, asyncState);
        }
        
        private object[] OnEndGetSqlString(System.IAsyncResult result) {
            string retVal = this.EndGetSqlString(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetSqlStringCompleted(object state) {
            if ((this.GetSqlStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetSqlStringCompleted(this, new GetSqlStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetSqlStringAsync(string sql) {
            this.GetSqlStringAsync(sql, null);
        }
        
        public void GetSqlStringAsync(string sql, object userState) {
            if ((this.onBeginGetSqlStringDelegate == null)) {
                this.onBeginGetSqlStringDelegate = new BeginOperationDelegate(this.OnBeginGetSqlString);
            }
            if ((this.onEndGetSqlStringDelegate == null)) {
                this.onEndGetSqlStringDelegate = new EndOperationDelegate(this.OnEndGetSqlString);
            }
            if ((this.onGetSqlStringCompletedDelegate == null)) {
                this.onGetSqlStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetSqlStringCompleted);
            }
            base.InvokeAsync(this.onBeginGetSqlStringDelegate, new object[] {
                        sql}, this.onEndGetSqlStringDelegate, this.onGetSqlStringCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override FactoriesCreator.SqlServiceReference.Service1Soap CreateChannel() {
            return new Service1SoapClientChannel(this);
        }
        
        private class Service1SoapClientChannel : ChannelBase<FactoriesCreator.SqlServiceReference.Service1Soap>, FactoriesCreator.SqlServiceReference.Service1Soap {
            
            public Service1SoapClientChannel(System.ServiceModel.ClientBase<FactoriesCreator.SqlServiceReference.Service1Soap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetSqlString(FactoriesCreator.SqlServiceReference.GetSqlStringRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetSqlString", _args, callback, asyncState);
                return _result;
            }
            
            public FactoriesCreator.SqlServiceReference.GetSqlStringResponse EndGetSqlString(System.IAsyncResult result) {
                object[] _args = new object[0];
                FactoriesCreator.SqlServiceReference.GetSqlStringResponse _result = ((FactoriesCreator.SqlServiceReference.GetSqlStringResponse)(base.EndInvoke("GetSqlString", _args, result)));
                return _result;
            }
        }
    }
}
